import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tailor-Brand-LogoMaker ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
   
    {children}
    </>
   
        
        
        
  );
}







